// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzlKnbvVjJAXX9WVLwnrcYhSkSomIGhc',
    appId: '1:664961683576:web:bdf5b4fa5c5a15f3bd5d8d',
    messagingSenderId: '664961683576',
    projectId: 'flutter-todo-a7bcc',
    authDomain: 'flutter-todo-a7bcc.firebaseapp.com',
    storageBucket: 'flutter-todo-a7bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb99uz7g5kOeKsgz5clhLsu_UeodGynko',
    appId: '1:664961683576:android:cf234a1444628f11bd5d8d',
    messagingSenderId: '664961683576',
    projectId: 'flutter-todo-a7bcc',
    storageBucket: 'flutter-todo-a7bcc.firebasestorage.app',
  );
}
